package TwoDayspackage;
import javax.swing.JOptionPane;
import java.sql.*;
import java.io.*;
import static TwoDayspackage.Chain.usernames;
import static TwoDayspackage.Chain.passwords;
import static TwoDayspackage.Chain.wallets;
import static TwoDayspackage.Chain.blockchain;
import static TwoDayspackage.Chain.zkpids;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author me
 */
public class ActionsFrame extends javax.swing.JFrame implements AllFrames{

    /**
     * Creates new form ActionsFrame
     */
    public ActionsFrame() {
        initComponents();
        System.gc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buyassets = new javax.swing.JButton();
        smtbutton = new javax.swing.JButton();
        validate = new javax.swing.JButton();
        addmoney = new javax.swing.JButton();
        sellassets = new javax.swing.JButton();
        viewbalance = new javax.swing.JButton();
        myassets = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHOOSE YOUR ACTIONS");

        buyassets.setText("BUY ASSETS");
        buyassets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyassetsActionPerformed(evt);
            }
        });

        smtbutton.setText("SHOW MY TRANSCATIONS");
        smtbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smtbuttonActionPerformed(evt);
            }
        });

        validate.setText("VALIDATE");
        validate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateActionPerformed(evt);
            }
        });

        addmoney.setText("ADD MONEY");
        addmoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmoneyActionPerformed(evt);
            }
        });

        sellassets.setText("SELL ASSETS");
        sellassets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellassetsActionPerformed(evt);
            }
        });

        viewbalance.setText("VIEW BALANCE");
        viewbalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbalanceActionPerformed(evt);
            }
        });

        myassets.setText("MY ASSETS");
        myassets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myassetsActionPerformed(evt);
            }
        });

        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sellassets, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(validate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buyassets, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(myassets, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(viewbalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(smtbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addmoney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buyassets)
                    .addComponent(smtbutton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(validate)
                    .addComponent(addmoney))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sellassets)
                    .addComponent(viewbalance))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myassets)
                    .addComponent(logout))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addmoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmoneyActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        am.setVisible(true);
    }//GEN-LAST:event_addmoneyActionPerformed

    private void sellassetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellassetsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        saf.setVisible(true);
    }//GEN-LAST:event_sellassetsActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        try{
            FileOutputStream fos0 = new FileOutputStream("D:\\4-2\\CRYPTO\\Assts\\2\\AssetManagement\\BlockChain.txt");
            ObjectOutputStream oos0 = new ObjectOutputStream(fos0);
            oos0.writeObject(blockchain);

            FileOutputStream fos1 = new FileOutputStream("D:\\4-2\\CRYPTO\\Assts\\2\\AssetManagement\\Usernames.txt");
            ObjectOutputStream oos1 = new ObjectOutputStream(fos1);
            oos1.writeObject(usernames);

            FileOutputStream fos2 = new FileOutputStream("D:\\4-2\\CRYPTO\\Assts\\2\\AssetManagement\\Passwords.txt");
            ObjectOutputStream oos2 = new ObjectOutputStream(fos2);
            oos2.writeObject(passwords);

            FileOutputStream fos3 = new FileOutputStream("D:\\4-2\\CRYPTO\\Assts\\2\\AssetManagement\\Wallets.txt");
            ObjectOutputStream oos3 = new ObjectOutputStream(fos3);
            oos3.writeObject(wallets);

            FileOutputStream fos4 = new FileOutputStream("D:\\4-2\\CRYPTO\\Assts\\2\\AssetManagement\\ZKPids.txt");
            ObjectOutputStream oos4 = new ObjectOutputStream(fos4);
            oos4.writeObject(zkpids);

            oos0.close();
            oos1.close();
            oos2.close();
            oos3.close();
            oos4.close();

            fos0.close();
            fos1.close();
            fos2.close();
            fos3.close();
            fos4.close();


        }catch(IOException e){

        }
        this.setVisible(false);
        lf.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void validateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateActionPerformed
        // TODO add your handling code here:
        //POPUP REQUIRED
        System.out.println("Calling chain.ischainvalid from validateactionbutton on action frame");
        try{Chain.isChainValid();}
        catch (Exception e){;}
    }//GEN-LAST:event_validateActionPerformed

    private void viewbalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbalanceActionPerformed
        // TODO add your handling code here:
        System.out.println("Calling chain.viewBalance from view balance button in action frame");
        int balance = Chain.viewBalance(LoginFrame.username);
        JOptionPane.showMessageDialog(null,"Your Wallet Balance is " + balance);
//        try{
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/crypto","root","OOPlite");
//            String sql = "select * from users where username=?";
//            PreparedStatement pstmt = conn.prepareStatement(sql);
//            pstmt.setString(1, LoginFrame.username);
//            ResultSet rs = pstmt.executeQuery();
//            if(rs.next()){
//                JOptionPane.showMessageDialog(null,"Your Wallet Balance is " + rs.getString("wallet"));
//            }
//            conn.close();
//        }
//        catch(Exception e){
//            JOptionPane.showMessageDialog(null, e);
//        }
    }//GEN-LAST:event_viewbalanceActionPerformed

    private void smtbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smtbuttonActionPerformed
        // TODO add your handling code here:
        if (!LoginFrame.username.equals(""))
            Chain.showMyTransactions(LoginFrame.username);
//        this.setVisible(false);
//        tf.setVisible(true);
    }//GEN-LAST:event_smtbuttonActionPerformed

    private void myassetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myassetsActionPerformed
        // TODO add your handling code here:
        if (!LoginFrame.username.equals(""))
            Chain.showMyAssets(LoginFrame.username);
//        this.setVisible(false);
//        yaf.setVisible(true);
    }//GEN-LAST:event_myassetsActionPerformed

    private void buyassetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyassetsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        baf.setVisible(true);
    }//GEN-LAST:event_buyassetsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                af.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addmoney;
    private javax.swing.JButton buyassets;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    private javax.swing.JButton myassets;
    private javax.swing.JButton sellassets;
    private javax.swing.JButton smtbutton;
    private javax.swing.JButton validate;
    private javax.swing.JButton viewbalance;
    // End of variables declaration//GEN-END:variables
}
