package TwoDayspackage;
import java.util.*;
import java.io.*;
import static TwoDayspackage.Chain.usernames;
import static TwoDayspackage.Chain.passwords;
import static TwoDayspackage.Chain.wallets;
import static TwoDayspackage.Chain.blockchain;
import static TwoDayspackage.Chain.zkpids;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author satvik
 */
public class BuyAssetFrame extends javax.swing.JFrame implements AllFrames {

    /**
     * Creates new form BuyAssetFrame
     */
    public static ArrayList<String> ass = new ArrayList<>(List.of("Asset 1 (30)", "Asset 2 (40)", "Asset 3 (20)", "Asset 4 (70)"));
    public BuyAssetFrame() {
        initComponents();
//        try{
//            
//            int i=0;
//            for(String name:usernames){
//                if(name.equals(LoginFrame.username)) break;
//                else i++;
//            }
//            Wallet uwallet = wallets.get(i);
//            assets.removeAllItems();
//            for(String asset : uwallet.assetList){
//                switch(asset){
//                    case "Asset1" : assets.addItem("Asset 1 (30)");break;
//                    case "Asset2" : assets.addItem("Asset 2 (40)");break;
//                    case "Asset3" : assets.addItem("Asset 3 (20)");break;
//                    case "Asset4" : assets.addItem("Asset 4 (70)");break;
//                }
//            }
//        }catch(Exception e){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BuyAssetButton = new javax.swing.JButton();
        AssetBack = new javax.swing.JButton();
        assets = new javax.swing.JComboBox<>();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter the asset you want to buy:");

        BuyAssetButton.setText("Buy");
        BuyAssetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyAssetButtonActionPerformed(evt);
            }
        });

        AssetBack.setText("Back");
        AssetBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssetBackActionPerformed(evt);
            }
        });

        assets.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asset 1 (30)", "Asset 2 (40)", "Asset 3 (20)", "Asset 4 (70)" }));
        assets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assetsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assets, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AssetBack, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuyAssetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AssetBack)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(BuyAssetButton)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AssetBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssetBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        af.setVisible(true);
    }//GEN-LAST:event_AssetBackActionPerformed

    private void assetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assetsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assetsActionPerformed

    private void BuyAssetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyAssetButtonActionPerformed
        // TODO add your handling code here:
//        if(new File("D:\\4-2\\CRYPTO\\Assts\\2\\ZKPids.txt").length() != 0){
//            int i=0;
//            for(String name:usernames){
//                if(name.equals(LoginFrame.username)) break;
//                else i++;
//            }
//            Wallet uwallet = wallets.get(i);
//            assets.removeAllItems();
//            for(String asset : uwallet.assetList){
//                switch(asset){
//                    case "Asset1" : assets.addItem("Asset 1 (30)");break;
//                    case "Asset2" : assets.addItem("Asset 2 (40)");break;
//                    case "Asset3" : assets.addItem("Asset 3 (20)");break;
//                    case "Asset4" : assets.addItem("Asset 4 (70)");break;
//                }
//            }
//        }
        if(Chain.login(LoginFrame.username)){
            String selectedItem = (String)assets.getSelectedItem();
            int selection = -1;
            selection = ass.indexOf(selectedItem);
    //        System.out.println(selectedItem + "\n" + selection);
            if(Chain.buyAssets(LoginFrame.username, selection)){
                assets.removeItem(selectedItem);
                ass.remove(selection);
    //            System.out.println("Adding to sell list : " + assets.getItemAt(selection) + "\n" + assets.getSelectedItem());
                SellAssetFrame.assets.addItem(selectedItem);
                System.out.println("assetList from frame after buying: " + ass);
            }
        }
            
            
    }//GEN-LAST:event_BuyAssetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyAssetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyAssetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyAssetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyAssetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                baf.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssetBack;
    private javax.swing.JButton BuyAssetButton;
    protected static javax.swing.JComboBox<String> assets;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
